# ruff: noqa: RUF001  # generated Markdown deliberately uses Chinese punctuation and typographic signs
"""Engine-side synthesis: support matrix, adoption timing, glossary "Implemented by" tables.

Layer 3 joins the two record types here and nowhere else (docs/engines/overview.md). Inputs:
`data/extracted/*.json` (models) and `data/extracted/engines/*.json` (engine snapshots).
Outputs, all deterministic and regenerated by `python -m llm_tech_matrix.synthesis.index`:

  data/reports/engine-support-matrix.md   models x engine snapshots, per-model details,
                                          integration version constraints
  data/reports/engine-adoption.md         when each tracked engine supported each model,
                                          using only dated, evidenced facts
  docs/glossary/<slug>.md / .zh.md        a generated "Implemented by (engines)" section per
                                          technique asserted in `technique_support[]`

Like the model index, only typed fields are read: `model_support[].support`,
`model_support[].model_details[]`, `technique_support[].glossary_slug`. Prose never produces a
row. The glossary sections sit between markers and are formatted with the same mdformat
extensions and `.mdformat.toml` options pre-commit uses, so the formatter and the generator cannot disagree.
"""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path

import mdformat

from .registry import EXTRACTED_DIR, REPO_ROOT

ENGINES_DIR = EXTRACTED_DIR / "engines"
GLOSSARY_DIR = REPO_ROOT / "docs" / "glossary"
UNKNOWN = "[Unknown/Not Disclosed]"
BANNER = "<!-- GENERATED by `uv run python -m llm_tech_matrix.synthesis.index` — do not edit by hand. -->"
MD_EXTENSIONS = {"gfm", "tables", "frontmatter"}
# The pre-commit hook reads .mdformat.toml; pass the same options so both produce identical text.
MD_OPTIONS = tomllib.loads((REPO_ROOT / ".mdformat.toml").read_text())
BEGIN = "<!-- BEGIN GENERATED: implemented-by-engines (synthesis.index) -->"
END = "<!-- END GENERATED: implemented-by-engines -->"
ROLE_ORDER = {"inference": 0, "training": 1, "rl_post_training": 2}
SUPPORT_LABEL = {
    "registered": "✅ registered",
    "model_specific": "🟡 model-specific",
    "delegated": "↪ delegated",
    "not_found": "✗ not found",
}
GLOSSARY_TEXT = {
    "en": {
        "heading": "## Implemented by (engines)",
        "intro": (
            "Generated from `technique_support[]` in the engine snapshots under "
            "[`data/extracted/engines/`](../../data/extracted/engines/) — do not edit. "
            '"Used by" above records models adopting the technique; this table records engines '
            "implementing it."
        ),
        "header": "| Engine snapshot | Roles | Implementation | Flags | Evidence |",
        "related": "## Related techniques",
    },
    "zh": {
        "heading": "## 实现此技术的引擎",
        "intro": (
            "由 [`data/extracted/engines/`](../../data/extracted/engines/) 中各引擎快照的 "
            "`technique_support[]` 自动生成，请勿手工编辑。上方表格记录采用该技术的模型，"
            "本表记录实现该技术的引擎。"
        ),
        "header": "| 引擎快照 | 角色 | 实现方式 | 参数 | 证据 |",
        "related": "## 相关技术",
    },
}


def load_engines(directory: Path | None = None) -> dict[str, dict]:
    directory = directory or ENGINES_DIR
    return {p.stem: json.loads(p.read_text()) for p in sorted(directory.glob("*.json"))}


def _engine_order(engines: dict[str, dict]) -> list[str]:
    # Group by primary role (listed first), so a training library that also ships an inference
    # stack sits with the training engines rather than between vLLM and SGLang.
    def key(slug: str) -> tuple:
        return (ROLE_ORDER[engines[slug]["metadata"]["roles"][0]], slug)

    return sorted(engines, key=key)


def _cell(text: str) -> str:
    return " ".join(str(text).split()).replace("|", "\\|") or "—"


def _evidence_link(url: str) -> str:
    label = "release notes" if "/releases/tag/" in url else url.rsplit("/", 1)[-1]
    return f"[{label}]({url})"


def _rows_by_model(engine: dict) -> dict[str, tuple[dict, dict | None]]:
    """Map model slug -> (architecture row, that model's model_details entry or None)."""
    out: dict[str, tuple[dict, dict | None]] = {}
    for row in engine["model_support"]:
        details = {d["model_slug"]: d for d in row.get("model_details", [])}
        for slug in row["model_slugs"]:
            out[slug] = (row, details.get(slug))
    return out


# ---------------------------------------------------------------- support matrix


def _glossary_title(slug: str, registry: dict) -> str:
    if slug in registry["techniques"]:
        return registry["techniques"][slug]["title"]
    path = GLOSSARY_DIR / f"{slug}.md"
    first = path.read_text().splitlines()[0] if path.exists() else ""
    return first.removeprefix("# ").strip() or slug


def render_support_matrix(
    extractions: dict[str, dict],
    engines: dict[str, dict],
    edges: dict[str, set[str]],
    registry: dict,
) -> str:
    order = _engine_order(engines)
    by_engine = {e: _rows_by_model(engines[e]) for e in order}
    models = sorted(
        extractions,
        key=lambda m: (
            extractions[m]["metadata"]["family"].lower(),
            extractions[m]["metadata"]["release_date"],
            m,
        ),
    )

    lines = [
        BANNER,
        "",
        "# Engine support matrix",
        "",
        f"{len(extractions)} model records × {len(order)} engine snapshots, generated from each snapshot's",
        "typed `model_support[]` rows. A cell answers *what does this engine release carry for this",
        "model's architecture?* — not *will it run*: a `not found` model may still load through a",
        "generic path (HF Transformers backends, FSDP on any HF model), which snapshots do not assess.",
        "",
        "- ✅ **registered** — in the engine's built-in model registry",
        "- 🟡 **model-specific** — no registry entry, but code or docs written for this architecture / model_type",
        "- ↪ **delegated** — the engine maps no HF architectures itself; the cell shows the named",
        "  delegate snapshot's support for the model (e.g. Megatron-LM → Megatron-Bridge)",
        "- ✗ **not found** — neither, verified across the repository at the pinned commit",
        "- — the snapshot has no row for this model (refresh the snapshot)",
        "",
        "## Snapshots",
        "",
        "| Snapshot | Roles | Release | Commit | Registered | Model-specific | Delegated | Not found |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for e in order:
        rec = engines[e]
        meta = rec["metadata"]
        counts = {k: 0 for k in SUPPORT_LABEL}
        for row in rec["model_support"]:
            counts[row["support"]] += len(row["model_slugs"])
        lines.append(
            f"| [`{e}`](../extracted/engines/{e}.md) | {', '.join(meta['roles'])} | "
            f"{meta['release_date']} | `{meta['commit_sha'][:7]}` | {counts['registered']} | "
            f"{counts['model_specific']} | {counts['delegated']} | {counts['not_found']} |"
        )

    lines += [
        "",
        "Counts are per model record: an architecture shared by several records counts once per record.",
    ]
    header = "| Model | Family | Released | " + " | ".join(f"`{e}`" for e in order) + " |"
    lines += [
        "",
        "## Matrix",
        "",
        header,
        "| --- | --- | --- | " + " | ".join("---" for _ in order) + " |",
    ]
    for m in models:
        meta = extractions[m]["metadata"]
        cells = []
        for e in order:
            hit = by_engine[e].get(m)
            if hit is None:
                cells.append("—")
                continue
            row, detail = hit
            label = SUPPORT_LABEL[row["support"]]
            if row["support"] == "delegated":
                target = by_engine.get(row["delegated_to"], {}).get(m)
                shown = SUPPORT_LABEL[target[0]["support"]] if target else "—"
                label = f"↪ `{row['delegated_to']}`: {shown}"
            elif detail and detail.get("since_version", UNKNOWN) != UNKNOWN:
                label += f" (since {detail['since_version']})"
            cells.append(label)
        lines.append(
            f"| [`{m}`](../extracted/{m}.md) | {meta['family']} | {meta['release_date']} | "
            + " | ".join(cells)
            + " |"
        )

    detail_rows = []
    for e in order:
        for m, (row, detail) in sorted(by_engine[e].items()):
            spec = ", ".join(f"`{s}`" for s in row.get("speculative_decoding", []))
            fields = {
                k: detail.get(k, UNKNOWN) if detail else UNKNOWN
                for k in ("since_version", "reasoning_parser", "tool_call_parser")
            }
            if not spec and all(v == UNKNOWN for v in fields.values()):
                continue
            shown = {k: (f"`{v}`" if v != UNKNOWN else "—") for k, v in fields.items()}
            detail_rows.append(
                f"| `{m}` | `{e}` | {spec or '—'} | {shown['since_version']} | "
                f"{shown['reasoning_parser']} | {shown['tool_call_parser']} |"
            )
    lines += [
        "",
        "## Techniques × engines",
        "",
        "Model-side edges (from the registry's typed slots) next to engine-side assertions",
        "(`technique_support[].glossary_slug`). **A blank engine cell means not asserted, not",
        "absent.** Snapshots record techniques that are model-specific or recently introduced, so",
        "commodity ones (GQA, YaRN, FIM) are blank by scope, and some are implemented in a dependency",
        "(a kernel library, Megatron) rather than in the tracked repository. Prose-only techniques",
        "have no typed model slot, so their model count is not computed.",
        "",
        "| Technique | Models using | " + " | ".join(f"`{e}`" for e in order) + " |",
        "| --- | --- | " + " | ".join("---" for _ in order) + " |",
        *_technique_rows(engines, order, edges, registry),
        "",
        "## Per-model details",
        "",
        "Architecture-level speculative-decoding handling, plus per-model facts the engine's own docs",
        "or release notes state (`model_details[]`). A dash means not stated — not unsupported.",
        "",
        "| Model | Snapshot | Speculative decoding | Since | Reasoning parser | Tool parser |",
        "| --- | --- | --- | --- | --- | --- |",
        *detail_rows,
        "",
        "## Integrations between tracked engines",
        "",
        "Version requirements one snapshot states for another tracked engine, one entry per source.",
        "Sources often disagree; they are listed side by side, not reconciled.",
        "",
        "| Snapshot | Relation | Counterpart | Version constraints |",
        "| --- | --- | --- | --- |",
    ]
    for e in order:
        for integ in engines[e]["integrations"]:
            if not integ.get("engine_slug"):
                continue
            constraints = "<br>".join(_cell(c) for c in integ.get("version_constraints", [])) or "—"
            target = integ["engine_slug"]
            lines.append(
                f"| `{e}` | `{integ['relation']}` | [`{target}`](../extracted/engines/{target}.md) | {constraints} |"
            )
    lines.append("")
    return "\n".join(lines)


def _technique_rows(
    engines: dict[str, dict], order: list[str], edges: dict[str, set[str]], registry: dict
) -> list[str]:
    implemented = engine_technique_rows(engines)
    prose_only = set(registry["prose_only"]["entries"])
    slugs = sorted(
        {s for s, models in edges.items() if models} | set(implemented),
        key=lambda s: (-len(edges.get(s, ())), s),
    )
    rows = []
    for slug in slugs:
        used = "prose-only" if slug in prose_only else str(len(edges.get(slug, ())))
        by = {e for e, _ in implemented.get(slug, [])}
        cells = " | ".join("✅" if e in by else "" for e in order)
        rows.append(
            f"| [{_glossary_title(slug, registry)}](../../docs/glossary/{slug}.md) | {used} | {cells} |"
        )
    return rows


# ---------------------------------------------------------------- adoption timing


def _month_index(yyyy_mm: str) -> int | None:
    m = re.fullmatch(r"(\d{4})-(\d{2})(?:-\d{2})?", yyyy_mm or "")
    return int(m.group(1)) * 12 + int(m.group(2)) if m else None


ADOPTION_BUCKETS = {
    "added": "Added in this release",
    "supported": "Supported, first version unknown",
    "missing": "Missing ≥1 month after release",
    "same_month": "Not found, same month",
    "predates": "Not found, model is newer",
    "delegated": "Delegated to another engine",
    "undated": "Model date unknown",
}


def _adoption_cell(
    extraction: dict, engine: dict, row: dict, detail: dict | None
) -> tuple[str, str]:
    """(bucket, table cell) for one model at one engine snapshot."""
    meta = engine["metadata"]
    if row["support"] == "delegated":
        return "delegated", f"↪ `{row['delegated_to']}`"
    mi = _month_index(extraction["metadata"]["release_date"])
    ei = _month_index(meta["release_date"])
    supported = row["support"] != "not_found"
    if mi is None or ei is None:
        return "undated", "✅ (model undated)" if supported else "✗ (model undated)"
    elapsed = ei - mi
    if detail and detail.get("since_version") == meta["release_tag"]:
        return "added", f"🆕 added, +{elapsed} mo"
    if supported:
        return "supported", f"✅ ≤ +{elapsed} mo" if elapsed >= 0 else "✅ before model release"
    if elapsed >= 1:
        return "missing", f"✗ missing at +{elapsed} mo"
    if elapsed == 0:
        return "same_month", "· same month"
    return "predates", "· model newer"


def render_adoption(extractions: dict[str, dict], engines: dict[str, dict]) -> str:
    order = _engine_order(engines)
    by_engine = {e: _rows_by_model(engines[e]) for e in order}
    # Newest first; models without a parseable release date go last.
    models = sorted(
        extractions,
        key=lambda m: (-(_month_index(extractions[m]["metadata"]["release_date"]) or 0), m),
    )

    lines = [
        BANNER,
        "",
        "# Engine adoption timing",
        "",
        "**Question:** how soon after a model's release does each tracked engine carry support for",
        "it, and which models is it still missing?",
        "",
        "Only dated, evidenced facts are used, so precision is deliberately coarse. Model release",
        "dates are month-precision (`YYYY-MM`); engine release dates are days. `+N mo` is the engine",
        "snapshot's release month minus the model's release month.",
        "",
        "- 🆕 **added, +N mo** — the snapshot's `model_details[].since_version` is its own tag (its",
        "  release notes list the model as new): support first shipped in this release.",
        "- ✅ **≤ +N mo** — supported (`registered` or `model_specific`) but the first supporting",
        "  version is not recorded, so N is an upper bound on the lag.",
        "- ✗ **missing at +N mo** — `not found` in a release at least one calendar month after the model's.",
        "- · **same month** — `not found`, released the same month as the model; with month-precision",
        "  model dates the order is unknown, so this is not counted as missing.",
        "- · **model newer** — `not found`, but the model came out after this release.",
        "- ↪ **delegated** — the engine leaves HF model mapping to the named snapshot; read that",
        "  column instead. Never counted as missing.",
        "- — the snapshot has no row for this model.",
        "",
        "## By model (newest first)",
        "",
        "| Model | Released | " + " | ".join(f"`{e}`" for e in order) + " |",
        "| --- | --- | " + " | ".join("---" for _ in order) + " |",
    ]
    tallies = {e: dict.fromkeys(ADOPTION_BUCKETS, 0) for e in order}
    missing: dict[str, list[str]] = {}
    for m in models:
        cells = []
        for e in order:
            hit = by_engine[e].get(m)
            if hit is None:
                cells.append("—")
                continue
            bucket, cell = _adoption_cell(extractions[m], engines[e], *hit)
            tallies[e][bucket] += 1
            if bucket == "missing":
                missing.setdefault(m, []).append(f"`{e}` ({cell.removeprefix('✗ missing at ')})")
            cells.append(cell)
        lines.append(
            f"| [`{m}`](../extracted/{m}.md) | {extractions[m]['metadata']['release_date']} | "
            + " | ".join(cells)
            + " |"
        )

    lines += [
        "",
        "## By snapshot",
        "",
        "| Snapshot | Release | " + " | ".join(ADOPTION_BUCKETS.values()) + " |",
        "| --- | --- | " + " | ".join("---" for _ in ADOPTION_BUCKETS) + " |",
    ]
    for e in order:
        counts = " | ".join(str(n) for n in tallies[e].values())
        lines.append(f"| `{e}` | {engines[e]['metadata']['release_date']} | {counts} |")

    lines += [
        "",
        "## Still missing at least a month after release",
        "",
        "Candidates for the next snapshot refresh, or for a note that the model runs only through a",
        "generic path.",
        "",
        *(
            [
                f"- [`{m}`](../extracted/{m}.md) ({extractions[m]['metadata']['release_date']}) — "
                + ", ".join(where)
                for m, where in missing.items()
            ]
            or ["None."]
        ),
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------- glossary sections


def engine_technique_rows(engines: dict[str, dict]) -> dict[str, list[tuple[str, dict]]]:
    out: dict[str, list[tuple[str, dict]]] = {}
    for e in _engine_order(engines):
        for row in engines[e]["technique_support"]:
            out.setdefault(row["glossary_slug"], []).append((e, row))
    return out


def _section(rows: list[tuple[str, dict]], engines: dict[str, dict], lang: str) -> str:
    t = GLOSSARY_TEXT[lang]
    body = [
        BEGIN,
        "",
        t["heading"],
        "",
        t["intro"],
        "",
        t["header"],
        "| --- | --- | --- | --- | --- |",
    ]
    for e, row in rows:
        roles = ", ".join(engines[e]["metadata"]["roles"])
        flags = "<br>".join(f"`{_cell(f)}`" for f in row.get("flags", [])) or "—"
        evidence = ", ".join(_evidence_link(u) for u in row["evidence"][:2])
        body.append(
            f"| [`{e}`](../../data/extracted/engines/{e}.md) | {roles} | {_cell(row['implementation'])} | "
            f"{flags} | {evidence} |"
        )
    return "\n".join([*body, "", END])


def render_glossary_file(
    path: Path, rows: list[tuple[str, dict]] | None, engines: dict[str, dict]
) -> str:
    """The glossary file's text with its generated section inserted, replaced or removed."""
    lang = "zh" if path.name.endswith(".zh.md") else "en"
    text = path.read_text()
    if BEGIN in text:
        head, rest = text.split(BEGIN, 1)
        tail = rest.split(END, 1)[1]
        text = head.rstrip("\n") + "\n\n" + tail.lstrip("\n")
    if rows:
        section = _section(rows, engines, lang)
        related = GLOSSARY_TEXT[lang]["related"]
        if related in text:
            head, tail = text.split(related, 1)
            text = head.rstrip("\n") + "\n\n" + section + "\n\n" + related + tail
        else:
            text = text.rstrip("\n") + "\n\n" + section + "\n"
    return mdformat.text(text, options=MD_OPTIONS, extensions=MD_EXTENSIONS)


def glossary_targets(engines: dict[str, dict]) -> dict[Path, str]:
    """Every glossary file whose content the generator owns (sections to add, keep or remove)."""
    rows = engine_technique_rows(engines)
    targets: dict[Path, str] = {}
    for path in sorted(GLOSSARY_DIR.glob("*.md")):
        slug = path.name.removesuffix(".md").removesuffix(".zh")
        if slug in ("README", "_template"):
            continue
        if slug in rows or BEGIN in path.read_text():
            targets[path] = render_glossary_file(path, rows.get(slug), engines)
    return targets
