"""Generate the browse surfaces from extracted records.

Outputs, all deterministic from `data/extracted/*.json` + `docs/glossary/registry.json`:

  data/extracted/README.md        model index (the browse surface the repo lacked)
  data/reports/technique-index.md technique <-> model matrix, both directions
  data/reports/coverage.md        gaps: drift, unbacked rows, prose-only entries

Run: `uv run python -m llm_tech_matrix.synthesis.index`
Never hand-edit the outputs; change the JSON, the registry, or this file.
"""

from __future__ import annotations

import re

from .registry import (
    EXTRACTED_DIR,
    REPO_ROOT,
    build_edges,
    dig,
    load_extractions,
    load_registry,
)

REPORTS_DIR = REPO_ROOT / "data" / "reports"
GLOSSARY_DIR = REPO_ROOT / "docs" / "glossary"
BANNER = "<!-- GENERATED by `uv run python -m llm_tech_matrix.synthesis.index` — do not edit by hand. -->"


def _meta(record: dict) -> dict:
    return record.get("metadata", {})


def _glossary_entries() -> list[str]:
    return sorted(
        p.stem
        for p in GLOSSARY_DIR.glob("*.md")
        if not p.name.endswith(".zh.md") and p.stem not in ("README", "_template")
    )


def _hand_usedby(slug: str, models: set[str]) -> dict[str, str]:
    """Model slug -> the parenthetical annotation on its 'Used by' row (may be empty).

    Rows like `Kimi K3 (via KDA)` or `Qwen3.8-Flash-Next (compared against)` document a
    *lineage or contrast*, not an adoption. The annotation is what tells the two apart,
    so it is carried through rather than discarded.
    """
    path = GLOSSARY_DIR / f"{slug}.md"
    if not path.exists():
        return set()
    text = path.read_text()
    if "## Used by" not in text:
        return set()
    section = text.split("## Used by", 1)[1].split("\n## ", 1)[0]
    rows = [ln for ln in section.splitlines() if ln.startswith("|")][2:]
    out: dict[str, str] = {}
    for row in rows:
        cell = row.split("|")[1].strip()
        note = ""
        if (m := re.search(r"\(([^)]*)\)", cell)) and not m.group(1).strip().startswith(
            "K2-Thinking"
        ):
            note = m.group(1).strip()
        norm = cell.split("(")[0].strip().lower().replace(" ", "-")
        if norm in models:
            out[norm] = note
        else:  # grouped rows like "GLM-5 / GLM-5.1" or "Kimi K2 family (...)"
            for token in re.split(r"[/,]", cell.split("(")[0]):
                tok = token.strip().lower().replace(" ", "-")
                if tok in models:
                    out[tok] = note
            for token in re.split(r"[/,]", note):
                tok = token.strip().lower().replace(" ", "-").replace("kimi-", "kimi-")
                if tok in models:
                    out[tok] = note
    return out


def render_model_index(extractions: dict[str, dict], edges: dict[str, set[str]]) -> str:
    by_model: dict[str, list[str]] = {m: [] for m in extractions}
    for slug, models in edges.items():
        for m in models:
            by_model[m].append(slug)

    rows = []
    for slug, record in sorted(
        extractions.items(),
        key=lambda kv: (
            _meta(kv[1]).get("release_date", "").startswith("["),  # undisclosed dates last
            _meta(kv[1]).get("release_date", ""),
            kv[0],
        ),
        reverse=True,
    ):
        m = _meta(record)
        params = m.get("params_total", "")
        # params_total can carry a long provenance note; keep the leading figure
        params = params.split("(")[0].strip()
        active = m.get("params_active", "").split("(")[0].strip()
        size = params if params == active else f"{params} / {active} active"
        techs = ", ".join(f"[{t}](../../docs/glossary/{t}.md)" for t in sorted(by_model[slug])[:6])
        if len(by_model[slug]) > 6:
            techs += f" +{len(by_model[slug]) - 6}"
        rows.append(
            f"| [`{slug}`]({slug}.md) | {m.get('family', '')} | {m.get('release_date', '')} | "
            f"{size} | {m.get('openness', '')} | {techs} |"
        )

    return "\n".join(
        [
            BANNER,
            "",
            "# Extracted models",
            "",
            f"{len(extractions)} records, newest first. Each row links to the rendered English",
            "summary; the same directory holds `<slug>.zh.md` (Chinese) and `<slug>.json`",
            "(the canonical data every other layer reads).",
            "",
            "The **Techniques** column is generated from typed schema fields only — see",
            "[`data/reports/technique-index.md`](../reports/technique-index.md) for the full",
            "matrix and [`docs/glossary/registry.json`](../../docs/glossary/registry.json) for",
            "the vocabulary that maps field values to glossary entries.",
            "",
            "| Model | Family | Released | Params | Openness | Techniques (structured) |",
            "| --- | --- | --- | --- | --- | --- |",
            *rows,
            "",
        ]
    )


def render_technique_index(
    extractions: dict[str, dict], edges: dict[str, set[str]], registry: dict
) -> str:
    lines = [
        BANNER,
        "",
        "# Technique index",
        "",
        "Technique <-> model edges derived from **typed schema fields**, not prose.",
        "",
        'A typed slot is an assertion (`sparse_attention.kind = "dsa"`); prose is often a',
        'mention (*"unlike MLA..."*, *"the family report documents Muon but 5.2 does not',
        'restate it"*). Only assertions appear here, which is why this file can be trusted',
        "as data and regenerated without review.",
        "",
        f"**{sum(len(v) for v in edges.values())} edges** over "
        f"{len([v for v in edges.values() if v])} techniques and {len(extractions)} models.",
        "",
        "Glossary entries whose adoption is only ever stated in free text are *not* here —",
        "they have no typed slot to read. See [coverage.md](./coverage.md).",
        "",
        "## By technique",
        "",
        "| Technique | Models | Count |",
        "| --- | --- | --- |",
    ]
    for slug in sorted(edges, key=lambda s: (-len(edges[s]), s)):
        models = sorted(edges[slug])
        if not models:
            continue
        title = registry["techniques"][slug]["title"]
        links = ", ".join(f"[`{m}`](../extracted/{m}.md)" for m in models)
        lines.append(f"| [{title}](../../docs/glossary/{slug}.md) | {links} | {len(models)} |")

    by_model: dict[str, list[str]] = {m: [] for m in extractions}
    for slug, models in edges.items():
        for m in models:
            by_model[m].append(slug)

    lines += ["", "## By model", "", "| Model | Techniques | Count |", "| --- | --- | --- |"]
    for model in sorted(by_model, key=lambda m: (-len(by_model[m]), m)):
        techs = sorted(by_model[model])
        links = ", ".join(f"[{t}](../../docs/glossary/{t}.md)" for t in techs)
        lines.append(f"| [`{model}`](../extracted/{model}.md) | {links} | {len(techs)} |")
    lines.append("")
    return "\n".join(lines)


def render_coverage(
    extractions: dict[str, dict],
    edges: dict[str, set[str]],
    unregistered: list[tuple[str, str, str]],
    registry: dict,
) -> str:
    models = set(extractions)
    entries = _glossary_entries()
    prose_only = set(registry["prose_only"]["entries"])

    lines = [
        BANNER,
        "",
        "# Coverage report",
        "",
        "What the generated index can and cannot see. This is the review queue: every",
        "section below is either a gap to close or a deliberate limitation to remember.",
        "",
        "## 1. Vocabulary drift",
        "",
    ]
    if unregistered:
        lines += [
            "Values in a registered slot that the registry does not know. Each is either a",
            "new technique needing a glossary entry, or drift needing an alias.",
            "",
            "| Model | Slot | Value |",
            "| --- | --- | --- |",
            *[f"| `{m}` | `{s}` | `{v}` |" for m, s, v in unregistered],
            "",
        ]
    else:
        lines += ["None — every value in a registered slot resolves to a glossary entry.", ""]

    lines += [
        "## 2. Glossary entries with no typed slot (hand-maintained by design)",
        "",
        "The schema types the *architecture* axis. Optimizer, RL method, MoE routing and",
        'training tricks live in free-text fields, so these entries\' "Used by" tables cannot',
        "be generated and must stay hand-maintained. Promoting any of them to a typed slot",
        "is a schema change, not a registry change.",
        "",
        ", ".join(f"[`{e}`](../../docs/glossary/{e}.md)" for e in sorted(prose_only)),
        "",
        '## 3. Structured edges missing from a "Used by" table',
        "",
        "The data asserts it; the glossary table does not list it. These are safe additions.",
        "",
    ]
    missing_rows = []
    annotated_rows = []
    unexplained_rows = []
    for slug in sorted(edges):
        if slug not in entries:
            continue
        hand = _hand_usedby(slug, models)
        auto = edges[slug]
        for m in sorted(auto - set(hand)):
            missing_rows.append(f"| [`{slug}`](../../docs/glossary/{slug}.md) | `{m}` |")
        for m in sorted(set(hand) - auto):
            row = f"| [`{slug}`](../../docs/glossary/{slug}.md) | `{m}` | {hand[m] or '—'} |"
            (annotated_rows if hand[m] else unexplained_rows).append(row)

    lines += (
        ["| Technique | Model |", "| --- | --- |", *missing_rows, ""]
        if missing_rows
        else ["None — every structured edge is already reflected in the glossary.", ""]
    )

    lines += [
        '## 4. "Used by" rows with no structured backing',
        "",
        "Listed in a glossary table but not asserted by any typed field. Two very different",
        "cases, so they are split.",
        "",
        "### 4a. Annotated cross-references — working as intended",
        "",
        "The row carries a parenthetical saying it is a lineage or contrast note, not an",
        "adoption: *(via KDA)*, *(compared against)*, *(convergent)*. These **should** have no",
        "structured edge — asserting one would claim the model uses a technique it does not.",
        "Keeping them is what makes the glossary readable; keeping them *unmarked* is what",
        "would make it wrong.",
        "",
    ]
    lines += (
        ["| Technique | Model | Annotation |", "| --- | --- | --- |", *annotated_rows, ""]
        if annotated_rows
        else ["None.", ""]
    )
    lines += [
        "### 4b. Unexplained — review these",
        "",
        "No annotation and no typed backing. Either the row is prose-derived (fine, but the",
        "reason is invisible), the extraction is missing a typed value (fix the JSON), or the",
        "row is wrong (fix the table).",
        "",
    ]
    lines += (
        ["| Technique | Model | Annotation |", "| --- | --- | --- |", *unexplained_rows, ""]
        if unexplained_rows
        else ["None.", ""]
    )

    unknown_slots = []
    for slot in registry["slots"]:
        for model, record in sorted(extractions.items()):
            for value in dig(record, slot):
                if isinstance(value, str) and value.startswith("[Unknown"):
                    unknown_slots.append(f"| `{model}` | `{slot}` |")
    lines += [
        "## 5. Undisclosed typed slots",
        "",
        "Registered slots holding `[Unknown/Not Disclosed]` — vendor disclosure gaps, not",
        "extraction gaps. Tracked so the index's silence is legible.",
        "",
    ]
    lines += (
        ["| Model | Slot |", "| --- | --- |", *unknown_slots, ""]
        if unknown_slots
        else ["None.", ""]
    )
    return "\n".join(lines)


def main() -> None:
    registry = load_registry()
    extractions = load_extractions()
    edges, unregistered = build_edges(extractions, registry)

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    targets = {
        EXTRACTED_DIR / "README.md": render_model_index(extractions, edges),
        REPORTS_DIR / "technique-index.md": render_technique_index(extractions, edges, registry),
        REPORTS_DIR / "coverage.md": render_coverage(extractions, edges, unregistered, registry),
    }
    for path, content in targets.items():
        path.write_text(content)
        print(f"Wrote {path.relative_to(REPO_ROOT)}")
    print(
        f"  {sum(len(v) for v in edges.values())} edges, {len(unregistered)} unregistered value(s)"
    )


if __name__ == "__main__":
    main()
